name: voo
description: voo ui
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^4.0.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: voo
      fonts:
        - asset: fonts/iconfont.ttf
          style: italic

  assets:
    - assets/error_page/